// <auto-generated />
using System;
using Axiom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Axiom.Infrastructure.Migrations
{
    [DbContext(typeof(AxiomDbContext))]
    [Migration("20260619012619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Axiom.Domain.Entities.AxiomSystem", b =>
                {
                    b.Property<long>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SystemId"));

                    b.Property<string>("EAI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SystemId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Systems_OwnerUserId");

                    b.ToTable("Systems", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IncidentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RitmNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IssueId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Issues_CreatedByUserId");

                    b.HasIndex("IncidentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Issues_IncidentNumber")
                        .HasFilter("[IncidentNumber] IS NOT NULL");

                    b.HasIndex("RitmNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Issues_RitmNumber")
                        .HasFilter("[RitmNumber] IS NOT NULL");

                    b.HasIndex("StateId")
                        .HasDatabaseName("IX_Issues_StateId");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("IX_Issues_SystemId");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.IssueState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("StateId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_IssueStates_Code");

                    b.ToTable("IssueStates", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KnowledgeStateId")
                        .HasColumnType("int");

                    b.Property<long>("KnowledgeTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("KnowledgeId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Knowledges_CreatedByUserId");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("IX_Knowledges_IssueId");

                    b.HasIndex("KnowledgeStateId")
                        .HasDatabaseName("IX_Knowledges_KnowledgeStateId");

                    b.HasIndex("KnowledgeTypeId")
                        .HasDatabaseName("IX_Knowledges_KnowledgeTypeId");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("IX_Knowledges_SystemId");

                    b.ToTable("Knowledges", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeKnowledgeTag", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("KnowledgeTagId")
                        .HasColumnType("bigint");

                    b.HasKey("KnowledgeId", "KnowledgeTagId");

                    b.HasIndex("KnowledgeTagId");

                    b.ToTable("KnowledgeKnowledgeTags", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("StateId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_KnowledgeStates_Code");

                    b.ToTable("KnowledgeStates", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeTag", b =>
                {
                    b.Property<long>("KnowledgeTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KnowledgeTagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("KnowledgeTagId");

                    b.HasIndex("TagName")
                        .IsUnique()
                        .HasDatabaseName("IX_KnowledgeTags_TagName");

                    b.ToTable("KnowledgeTags", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeType", b =>
                {
                    b.Property<long>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("TypeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_KnowledgeTypes_Code");

                    b.ToTable("KnowledgeTypes", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Axiom.Domain.Entities.AxiomSystem", b =>
                {
                    b.HasOne("Axiom.Domain.Entities.User", "Owner")
                        .WithMany("OwnedSystems")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.Issue", b =>
                {
                    b.HasOne("Axiom.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedIssues")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Axiom.Domain.Entities.IssueState", "State")
                        .WithMany("Issues")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Axiom.Domain.Entities.AxiomSystem", "System")
                        .WithMany("Issues")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("State");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.Knowledge", b =>
                {
                    b.HasOne("Axiom.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedKnowledges")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Axiom.Domain.Entities.Issue", "Issue")
                        .WithMany("Knowledges")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Axiom.Domain.Entities.KnowledgeState", "State")
                        .WithMany("Knowledges")
                        .HasForeignKey("KnowledgeStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Axiom.Domain.Entities.KnowledgeType", "Type")
                        .WithMany("Knowledges")
                        .HasForeignKey("KnowledgeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Axiom.Domain.Entities.AxiomSystem", "System")
                        .WithMany("Knowledges")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Issue");

                    b.Navigation("State");

                    b.Navigation("System");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeKnowledgeTag", b =>
                {
                    b.HasOne("Axiom.Domain.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeKnowledgeTags")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Axiom.Domain.Entities.KnowledgeTag", "Tag")
                        .WithMany("KnowledgeKnowledgeTags")
                        .HasForeignKey("KnowledgeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.AxiomSystem", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Knowledges");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Knowledges");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.IssueState", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.Knowledge", b =>
                {
                    b.Navigation("KnowledgeKnowledgeTags");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeState", b =>
                {
                    b.Navigation("Knowledges");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeTag", b =>
                {
                    b.Navigation("KnowledgeKnowledgeTags");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.KnowledgeType", b =>
                {
                    b.Navigation("Knowledges");
                });

            modelBuilder.Entity("Axiom.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedIssues");

                    b.Navigation("CreatedKnowledges");

                    b.Navigation("OwnedSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
